// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2adpgv2zn5CDU6qamMPbrBVCdFj_0vo',
    appId: '1:293015566873:web:c583faab27b7fe566b4888',
    messagingSenderId: '293015566873',
    projectId: 'finance-35405',
    authDomain: 'finance-35405.firebaseapp.com',
    storageBucket: 'finance-35405.firebasestorage.app',
    measurementId: 'G-9ZSP2KP8QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADHsKfDSBEQxvsX3Xeanrlsc11lgfnFMc',
    appId: '1:293015566873:android:63c01de63b10d14c6b4888',
    messagingSenderId: '293015566873',
    projectId: 'finance-35405',
    storageBucket: 'finance-35405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFhRzwmPwoTat3x2CPCMyIHPoa9yLna4Q',
    appId: '1:293015566873:ios:4e4518e409cf1ca76b4888',
    messagingSenderId: '293015566873',
    projectId: 'finance-35405',
    storageBucket: 'finance-35405.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFhRzwmPwoTat3x2CPCMyIHPoa9yLna4Q',
    appId: '1:293015566873:ios:4e4518e409cf1ca76b4888',
    messagingSenderId: '293015566873',
    projectId: 'finance-35405',
    storageBucket: 'finance-35405.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN2adpgv2zn5CDU6qamMPbrBVCdFj_0vo',
    appId: '1:293015566873:web:c2a0123d70aa282b6b4888',
    messagingSenderId: '293015566873',
    projectId: 'finance-35405',
    authDomain: 'finance-35405.firebaseapp.com',
    storageBucket: 'finance-35405.firebasestorage.app',
    measurementId: 'G-7B2SDQ0TNC',
  );
}
